version: '3'
services:
  antink-server:
    build: .
    container_name: antink-server
    privileged: true
    devices:
      - /dev/fuse
    volumes:
      - ./it24_host:/it24_host:ro
      - ./antink_mount:/antink_mount
      - ./antink_logs:/var/log

  antink-logger:
    image: alpine
    container_name: antink-logger
    command: sh -c "tail -f /var/log/it24.log"
    volumes:
      - ./antink_logs:/var/log
    depends_on:
      - antink-server
